name: CI tests

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
      - name: Test & publish code coverage
      # Publish code coverage on Code Climate
      # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v2.7.5
      # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_COVERAGE_KEY }}
        with:
          coverageCommand: make test-coverage
          debug: true
